# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabotapp', '0006_auto_20170821_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudwatchConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('aws_access_key_id', models.CharField(max_length=2000)),
                ('aws_secret_access_key', models.CharField(max_length=2000)),
                ('aws_session_token', models.CharField(blank=True, max_length=2000)),
                ('aws_region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CloudwatchStatusCheck',
            fields=[
                ('statuscheck_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cabotapp.StatusCheck')),
                ('cloudwatch_metric', models.TextField(help_text=b'Full metric name (<Namespace>:<Metric>) for any cloudwatch metric.')),
                ('dimensions', models.CharField(max_length=2000)),
                ('statistic', models.CharField(choices=[(b'SampleCount', b'SampleCount'), (b'Average', b'Average'), (b'Sum', b'Sum'), (b'Minimum', b'Minimum'), (b'Maximum', b'Maximum')], max_length=2000)),
                ('cloudwatch_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabot_check_cloudwatch.CloudwatchConfig')),
            ],
            options={
                'abstract': False,
            },
            bases=('cabotapp.statuscheck',),
        ),
    ]
